package com.evcall.mobp2p.constant;
/**
 * 统一作为handler发送消息的what值
 * @author Liu
 *
 */
public enum HandlerType {
	TOAST_LONG,
	TOAST_SHORT,
	
	//登录相关
	LOGIN_DISCONNECT,
	LOGIN_CONNECTING,
	LOGIN_CONNECTED,
	LOGIN_CONNECT_BUSY,
	LOGIN_CONNECT_FAIL,
	LOGIN_RECONNECT,
	LOGIN_SUCCESS,
	LOGIN_OUT,
	LOGIN_FAIL,
	LOGIN_INIT,
	LOGIN_LOADING,
	CENTER_SERVER_CLOSE,
	CENTER_SERVER_OPEN,
	
	//网络连接
	NET_CONNECTED,
	NET_ERROR,
	
	//设备信息
	DEVICE_LOGINING,
	DEVICE_STATE_UPDATE,
	
	//业务数据
	UPDATE_BUSINESS,
	
	//设置按钮启用
	SETTING_BTN_ENABLED,
	
	//客服反呼
	SERVER_BACKCALL,
	
	//呼叫请求
	CALL_REQUEST,
	CALL_HANGUP,
	
	//客户列表
	CUSTOM_UPDATE,
	
	//推送消息
	MSG_UPDATE,

	//视频通话
	INDEX_CONNECTING,
	INDEX_UPDATE,
	INDEX_LINEUP,
	INDEX_LINEUP_RESPONSE,
	INDEX_ANSWER,
	SERVER_ENTER,
	SERVER_EXIT,
	TALK_ENTER,
	TALK_REMOTE_SIZE,
	TALK_EXCEPTIONE,
	TALK_PAUSE_REVER,
	TALK_AUDIO_VIDEO,
	TALK_SHARE_RESOURCE_SHOW,
	TALK_SHARE_RESOURCE_CLOSE,
	TALK_SHARE_RESOURCE_WAITING,
	TALK_SHARE_RESOURCE_DOWNING,
	TALK_SHARE_RESOURCE_FAIL,
	TALK_SHARE_RESOURCE_SUCCESS,
	TALK_SIGN_SHOW,
	TALK_SIGN_CLOSE,
	TALK_EXIT_WAITING,
	TALK_EXIT_SUCCESS,

	//消息类型
	MSG_BUSINESS_UPDAING,
	MSG_BUSINESS_FINISH,
}
